basdat_c03/urls.py
from django.contrib import admin
from django.urls import path, include
import homepage.urls
import kategori_apparel.urls
import koleksi.urls
import koleksi_tokoh.urls
import registrasiPengguna.urls
import login.urls

#Karlina
import pekerjaan.urls
import bekerja.urls
import menggunakan_barang.urls

#Avel
import makanan.urls
import makan.urls
#import misi.urls
#import menjalankan_misi_utama.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include(login.urls)),
    path('registrasiPengguna/', include(registrasiPengguna.urls)),
    path('kategori_apparel/', include(kategori_apparel.urls)),
    path('koleksi/', include(koleksi.urls)),
    path('koleksi_tokoh/', include(koleksi_tokoh.urls)),

    #Karlina
    path('pekerjaan/', include(pekerjaan.urls)),
    path('bekerja/', include(bekerja.urls)),
    path('menggunakan_barang/', include(menggunakan_barang.urls)),

    #Avel
    path('makanan/', include(makanan.urls)),
    path('makan/', include(makan.urls)),
    #path('misi/', include(misi.urls)),
    #path('menjalankan_misi_utama/', include(menjalankan_misi_utama.urls)),
]

koleksi/urls.py
from django.urls import path
from .views import *

app_name = 'koleksi'
urlpatterns = [
	path('', rud_koleksi, name='koleksi'),
	path('create/', c_koleksi, name='c_koleksi'),
	path('delete/<id>/<harga>/',d_koleksi, name='d_koleksi'),
]

misi/urls.py
from django.urls import path
from misi.views import *

app_name = 'misi'
urlpattern = [
    path('', read_misi_utama),
    path('create/', create_misi_utama),
]

koleksi/models.py
from django.db import models

# Create your models here.

koleksi/forms.py
from django import forms
from django.db import connection

search_path = "SET search_path to THECIMS"

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def get_id_koleksi():
    with connection.cursor() as c:
        c.execute(search_path)
        c.execute("SELECT id FROM KOLEKSI")
        res = dictfetchall(c)
    temp_res = [res[i]['id'] for i in range(len(res))]
    return [tuple([i,i]) for i in temp_res]

class createForm(forms.Form):

    # id = forms.CharField(label="ID", widget=forms.Select(choices=get_id_koleksi()))
    id = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ID',
        'type' : 'text',
        'required': True,
    }))

    harga = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Harga',
        'type' : 'integer',
        'required': True,
    }))

koleksi/views.py
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import createForm

def rud_koleksi(request):
    cursor = connection.cursor()
    try:
        cursor.execute("SET SEARCH_PATH TO THECIMS")
        cursor.execute("SELECT * FROM KOLEKSI")
        result = namedtuplefetchall(cursor)
    except Exception as e:
        print(e)
    finally:
        cursor.close()

    return render(request, 'koleksi/index.html', {'result': result})

def c_koleksi(request):
    # if request.session['role'] != 'admin':
    #     return HttpResponseRedirect(reverse('/'))
    if request.method == 'POST':
        form = createForm(request.POST)
        if form.is_valid():
            id = form.cleaned_data['id']
            harga = form.cleaned_data['harga']
            with connection.cursor() as c:
                c.execute("SET SEARCH_PATH TO THECIMS")
                c.execute(f"INSERT INTO KOLEKSI VALUES ('{id}', {harga})")
        return HttpResponseRedirect(reverse('koleksi:koleksi'))
    create_form = createForm()
    response = {'create_form':create_form}
    return render(request,'koleksi/create.html',response)

def d_koleksi(request, id, harga):
    # if request.session['role'] != 'admin':
    #     return HttpResponseRedirect(reverse('/'))
    with connection.cursor() as c:
        c.execute("SET SEARCH_PATH TO THECIMS")
        c.execute("DELETE FROM KOLEKSI WHERE id = %s AND harga = %s", [id, harga])
    return HttpResponseRedirect(reverse('koleksi:koleksi'))

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

koleksi/templates/koleksi/create.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Koleksi</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
                color: rgb(0, 0, 0);
                margin-top: 40px;
                margin-bottom: 40px;
                text-align: center;
        }
        
        body {
            background: linear-gradient(110.7deg, #ecbb83 31.7%, #FFFFFF 93.54%);
            margin-left: 40px;
            margin-right: 50px;
        }
    </style>
</head>

<body>
    <div>
        <h1>Create Koleksi</h1>
    </div>
    <div>
        <form action='' method="POST" class="form-group">
        {% csrf_token %}
            {% for field in create_form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <div class="centre-items">
                <input type="submit" class="btn btn-dark" value="Create">
            </div>
        </form>
    </div>
</body>

</html>

koleksi/templates/koleksi/index.html
<html lang="en">

{% load static %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <style>
            h1 {
                color: rgb(0, 0, 0);
                margin-top: 40px;
                margin-bottom: 40px;
                text-align: center;
            }
            
            body {
                background: linear-gradient(110.7deg, #ecbb83 31.7%, #FFFFFF 93.54%);
                margin-left: 40px;
                margin-right: 50px;
            }

            .btn-green{
                background-color: white;
                color: #ecbb83;
                margin-right: 5px;
            }
        </style>
        <title>Koleksi</title>
    </head>

    <body>
        <div class="page-header">
            <h1>KOLEKSI</h1>
        </div>

        <div>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">No</th>
                        <th scope="col">ID Koleksi</th>
                        <th scope="col">Harga Koleksi</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for res in result %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ res.id }}</td>
                        <td>{{ res.harga }}</td>
                        <td>
                            <a href="/">
                                <button type="button" class=" btn btn-green" >
                                    UPDATE
                                </button>
                            </a>
                            <a href="{% url 'koleksi:d_koleksi' id=res.id harga=res.harga %}">
                                <button type="button" class=" btn btn-green" >
                                    DELETE
                                </button>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>

</html>