basdat_c03/urls.py
from django.contrib import admin
from django.urls import path, include
import homepage.urls
import kategori_apparel.urls
import koleksi.urls
import koleksi_tokoh.urls
import registrasiPengguna.urls
import login.urls

#Karlina
import pekerjaan.urls
import bekerja.urls
import menggunakan_barang.urls

#Avel
import makanan.urls
import makan.urls
#import misi.urls
#import menjalankan_misi_utama.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include(login.urls)),
    path('registrasiPengguna/', include(registrasiPengguna.urls)),
    path('kategori_apparel/', include(kategori_apparel.urls)),
    path('koleksi/', include(koleksi.urls)),
    path('koleksi_tokoh/', include(koleksi_tokoh.urls)),

    #Karlina
    path('pekerjaan/', include(pekerjaan.urls)),
    path('bekerja/', include(bekerja.urls)),
    path('menggunakan_barang/', include(menggunakan_barang.urls)),

    #Avel
    path('makanan/', include(makanan.urls)),
    path('makan/', include(makan.urls)),
    #path('misi/', include(misi.urls)),
    #path('menjalankan_misi_utama/', include(menjalankan_misi_utama.urls)),
]

misi/urls.py
from django.urls import path
from misi.views import *

app_name = 'misi'
urlpattern = [
    path('', read_misi_utama),
    path('create/', create_misi_utama),
]

pekerjaan/urls.py
from django.urls import path
from .views import *
from pekerjaan import views

app_name = 'pekerjaan'
urlpatterns = [
	path('', read, name='read'),
	path('create/', create_pekerjaan, name='create_pekerjaan'),
	path('update', update, name='update'),
	path('delete/<str:nama_pekerjaan>/', views.delete, name='delete'),
]

pekerjaan/models.py
from django.db import models

# Create your models here.

pekerjaan/forms.py
from django import forms

class pekerjaanForm(forms.Form):
    nama_pekerjaan = forms.CharField(label='Nama Pekerjaan', widget=forms.TextInput(attrs={
        'class': 'form-control col-md-6',
        'id': 'nama-pekerjaan',
        'placeholder': "Nama Pekerjaan"}))

    base_honor = forms.IntegerField(label='Base Honor', widget=forms.NumberInput(attrs={
        'class': 'form-control col-md-6',
        'id': 'base-honor',
        'placeholder': "Base Honor"}))

pekerjaan/views.py
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.shortcuts import redirect

from pekerjaan.forms import pekerjaanForm


#CRUD PEKERJAAN

				# cursor.execute("INSERT INTO PEKERJAAN VALUES(%s, %s)", [nama_pekerjaan, base_salary])
#Create
# def create_pekerjaan(request):
# 	if (request.method == "POST"):
# 		form = pekerjaanForm(request.POST)
# 		if (form.is_valid()):
# 			with connection.cursor() as c:
# 				nama_pekerjaan = request.POST['nama_pekerjaan']
# 				base_salary = request.POST['base_salary']
#                 c.execute(f"INSERT INTO PEKERJAAN VALUES ('{nama_pekerjaan}', {base_salary})")

# 			return redirect("/pekerjaan/")

# 	form = pekerjaanForm()
# 	response = {}
# 	response["pekerjaan_form"] = form
# 	return render(request, 'pekerjaan/create.html', response)

def create_pekerjaan(request):
    # if request.session['role'] != 'admin':
    #     return HttpResponseRedirect(reverse('/'))
    if request.method == 'POST':
        form = pekerjaanForm(request.POST)
        if form.is_valid():
            nama_pekerjaan = form.cleaned_data['nama_pekerjaan']
            base_honor = form.cleaned_data['base_honor']
            with connection.cursor() as c:
                c.execute("SET SEARCH_PATH TO THECIMS")
                c.execute(f"INSERT INTO PEKERJAAN VALUES ('{nama_pekerjaan}', {base_honor})")
        return HttpResponseRedirect(reverse('pekerjaan:read'))
    create_form = pekerjaanForm()
    response = {'create_form':create_form}
    return render(request,'pekerjaan/create.html',response)


#Read
def read(request):
    cursor = connection.cursor()

    try:
        cursor.execute("SET SEARCH_PATH TO THECIMS")
        cursor.execute("""SELECT *, case when nama in 
            (select p.nama from pekerjaan p, tokoh t, bekerja b, apparel a
            where p.nama = b.nama_pekerjaan and p.nama = t.pekerjaan and p.nama = a.nama_pekerjaan)
        then false
        else true
        end as deleteable
        from pekerjaan
        order by nama asc;""")

        result = namedtuplefetchall(cursor)
        

    except Exception as e:
        print(e)

    finally:
        cursor.close()

    return render(request, 'pekerjaan/read.html', {'result': result})

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

#Update
def update(request, pekerjaan):
    return render(request,'pekerjaan/update.html')
    # cursor = connection.cursor()
    # if request.session.has_key('username'):
    #     if request.session.role == 'Admin':
    #         print("pekerjaan = " + pekerjaan)
    #         res = cursor.execute(f"select * from pekerjaan where nama = '{pekerjaan}';")
            
    #         print(res[0])
    #         return render(request, 'update_job.html', {'result' : res[0]})
        
    #     else:
    #         return HttpResponseRedirect('/pekerjaan/')

    # else:
    #     return HttpResponseRedirect('/login')

#Delete
def delete(request, nama_pekerjaan) :
    print("delete  = " + nama_pekerjaan)

    if request.session.has_key ('username') :
        with connection.cursor() as cursor:
            if request.session['role'] == 'Admin' :
                cursor.execute (f"DELETE FROM PEKERJAAN WHERE nama = '{nama_pekerjaan}';")

            return redirect("/pekerjaan/")

    else:
        return HttpResponseRedirect('/login')

pekerjaan/templates/pekerjaan/create.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Pekerjaan</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
                color: rgb(0, 0, 0);
                margin-top: 40px;
                margin-bottom: 40px;
                text-align: center;
        }
        
        body {
            background: linear-gradient(110.7deg, #ecbb83 31.7%, #FFFFFF 93.54%);
            margin-left: 40px;
            margin-right: 50px;
        }
    </style>
</head>

<body>
    <div>
        <h1>Create Pekerjaan</h1>
    </div>
    <div>
        <form action='' method="POST" class="form-group">
        {% csrf_token %}
            {% for field in create_form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <div class="centre-items">
                <input type="submit" class="btn btn-dark" value="Create">
            </div>
        </form>
    </div>
</body>

</html>

pekerjaan/templates/pekerjaan/read.html
<html lang="en">
    {% block content %}
   <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <style>
            h1 {
                color: rgb(0, 0, 0);
                margin-top: 40px;
                margin-bottom: 40px;
                text-align: center;
            }
            
            body {
                background: linear-gradient(110.7deg, #ecbb83 31.7%, #FFFFFF 93.54%);
                margin-left: 40px;
                margin-right: 50px;
            }

            .btn-green{
                background-color: white;
                color: #ecbb83;
                margin-right: 5px;
            }   
        </style>
        <title>Pekerjaan</title>
    </head>

    <body>
        <div class="page-header">
            <h1>DAFTAR PEKERJAAN</h1>
        </div>
        <div>
            <table class="table">
                <thead class="thead-dark">
                    <tr scope="row">
                        <th scope="col">No</th>
                        <th scope="col">Nama Pekerjaan</th>
                        <th scope="col">Base Honor</th>

                   

                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    {% for res in result %}
                    <tr scope="row">
                        <td>{{ forloop.counter }}.</td>
                        <td>{{ res.nama }}</td>
                        <td>{{ res.base_honor }}</td>

              
                        <td>
                            <a href="/pekerjaan/update/">
                                <button type="button" class=" btn btn-green" >
                                    UPDATE
                                </button>
                            </a>
                            <a href="/pekerjaan/">
                                <button type="button" class=" btn btn-green" >
                                    DELETE
                                </button>
                            </a>
                        </td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
    {% endblock %}
</html>  






    

    

pekerjaan/templates/pekerjaan/update.html
<html lang="en"></html>
{% load static %}

{% block script %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'pekerjaan/style.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
{% endblock %}
{% block content %}
<body id="create">
	<div class="col-xs-12 container">
			<h1 class="title text-white">Update Pekerjaan</h1>
                <form id="form_pekerjaan" method="POST" class="Login-Form" action= "{% url 'pekerjaan:update' %}"autocomplete="text-center">
                
                    <div class="mb-3 d-flex gap-3 justify-content-center w-50 mx-auto">
                        <label for="nama">Nama Pekerjaan:</label>
                        <input type="text" class="form-control" id="nama" placeholder="Enter job name" name="nama">
                      </div>
                      <div class="mb-3 d-flex gap-3 justify-content-center w-50 mx-auto">
                        <label for="base">Base Salary:</label>
                        <input type="text" class="form-control" id="base" placeholder="Enter base salary" name="base">
                      </div>
                      <a href="/pekerjaan/read"><button class="btn btn-green" type="submit" 
                        value="Submit">SIMPAN</button></a>
		</form>
	</div>
</body>
{% endblock %}